name: Deploy to Firebase Hosting on push
on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup node base
        uses: ./.github/workflows/utils/setup-node
      - name: Install dependencies
        run: pnpm lint

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup node base
        uses: ./.github/workflows/utils/setup-node
      - name: Build app
        run: pnpm build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_EXEL_E7432 }}
          channelId: live
          projectId: exel-e7432
